---
services:
  backend:
    image: 4gray/iptvnator-backend:latest
    ports:
      - "7333:3000"
    environment:
      - CLIENT_URL=http://localhost:4333 
      # this one should match with the address and port in frontend CLIENT_URL env
      
  frontend: 
    # Use local build by default so `docker-compose up` will build the frontend
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: 4gray/iptvnator:latest
    ports:
      - "4333:80"
    environment:
      - BACKEND_URL=http://localhost:7333 
      # this one should match with the address of the backend service
      
